# Generated by Django 6.0.2 on 2026-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.CharField(default='Grade 6', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
